services:
  pocketnet.core:
    container_name: pocketnet.core
    image: pocketnetteam/pocketnet.core:latest
    restart: on-failure
    stop_grace_period: 10m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /pocketcoin:/home/pocketcore/.pocketcoin
    ports:
      - "37070:37070"
      - "38081:38081"
      - "38881:38881"
      - "8087:8087"
      - "8887:8887"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

  node-monitor:
    build:
      context: .
    image: comrada/pocketnet-node-monitor
    container_name: node-monitor
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - TELEGRAM_BOT_TOKEN=<paste-your-token>
      - TELEGRAM_CHAT_ID=<paste-your-chat-id>
      - RPC_HOST=pocketnet.core
      - RPC_PORT=8899
      - RPC_USER=user
      - RPC_PASSWORD=pass
      - RPC_TIMEOUT=60
      - INTERVAL_STACKING_REWARDS_SEC=120
      - INTERVAL_STACKING_MIN=60
      - INTERVAL_BALANCE_SEC=300
    depends_on:
      - pocketnet.core
