name: Build & Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Extract version from pyproject.toml
        id: version
        run: echo "VERSION=$(poetry version -s)" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/pocketnet-node-monitor:${{ steps.version.outputs.VERSION }}
            ${{ vars.DOCKERHUB_USERNAME }}/pocketnet-node-monitor:latest

      - name: Check if git tag exists
        id: tag_check
        run: |
          TAG="${{ steps.version.outputs.VERSION }}"
          if git ls-remote --tags origin "refs/tags/$TAG" | grep "$TAG" >/dev/null; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Git tag
        if: steps.tag_check.outputs.exists == 'false'
        run: |
          git config user.name "Comrada"
          git config user.email "comrada@proton.me"
          git tag "${{ steps.version.outputs.VERSION }}"
          git push origin "${{ steps.version.outputs.VERSION }}"
